### ISSUE TITLE
Duplicate post and corrupted database when saving a special character

### ISSUE THREAD

**Issue by robiso** [StephanStanisic/plugin-simpleblog#3]
Steps to reproduce ducplicate post behaviour:

1. Create a bloq title with the following letter: TestŽ. (wait for it to redirect to this new blog page and wait).
2. Check blog database, it's saved correctly.
3 After being redirected to the TestŽ page, click inside the post title and click outside.
4. An error will be seen, and the post/page will be duplicated with only the title in the database.

**Comment by robiso** [comment]
Here's the current state of my modifications to the awesome plugin you've created.
[simpleblog.zip](https://github.com/StephanStanisic/plugin-simpleblog/files/3537487/simpleblog.zip)

Please make sure to pull the latest experimental for this to work properly. :)

**Comment by StephanStanisic** [comment]
So this is the progress I've been making:

There is something with the URL Encoding: There seems to be a case of double encoding.

The problem lays with the method used to get the current page index. Because we use `window.location.pathname.split("/").pop()` to get the slug, it is URL encoded. We send this (double) url encoded value to PHP and with URL encoded characters that makes a mess.


```
$_POST["page"]
string(14) "nice-%E1%BA%91"
```

```
$Wcms->slugify($_POST["page"])
string(13) "nice-e1-ba-91"
```

```
$Wcms->slugify(urldecode($_POST["page"]))
string(8) "nice-ẑ"
```

I added a extra url decode into the javascript section as this is where this is a problem. Creating a pull request to close this issue.

Awesome work!
