### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by robiso** [StephanStanisic/plugin-simpleblog#5]
<img width="1920" alt="Screenshot 2019-09-25 at 21 35 52" src="https://user-images.githubusercontent.com/6200139/65633463-788fcd00-dfdc-11e9-8055-b72c3f658df0.png">

Currently, when i visit the "Blog" page, I'm greeted with the information above.
I believe this happens due to the nature of the 200 OK header, which comes after the 404 is already sent (if I watch the network tab).

Weirdly, another dev didn't have this error on their server.

Other than that, I think this is one of the most anticipated plugins since the beginning of WonderCMS. :) Kudos and nice work!

**Comment by StephanStanisic** [comment]
So what is happening here:

The plugin is trying to change the http status code to 200. WonderCMS changes the status code to 404, because the page doesn't exist.

Before any content get's send to the client, you can edit all the headers you like. Once you send something as large as a space (via `echo` etc), the body of the request has been started and no luck for changing the HTTP headers.

I thought that plugins and their listeners where getting loaded + executed before the start of any output, so I could change the headers inside the listeners.

I think that the difference between servers is gzip compression. When this is enabled, the server waits for a chunck of the page (including headers) has been generated, and only then starts transmitting. During this PHP can still edit the headers, because they are still on the server.

I'm not sure how we could make this work on non-gzip servers. The error could be hidden, but that doesn't solve the issue that google won't index the pages, since their status code is 404.

In some (small) projects where I do similar things, I've used output buffering to make sure that the code only get's send on the end of the page.

```
ob_start();

echo "Hi!";
header("content-type: text/plain"); // This doesn't work, normally

$result = ob_get_contents();
ob_end_clean();
echo $result;
```

This isn't ideal, since the complete page is getting buffered. This will result in slower server times, since PHP can't start sending data while it is still running. 

I don't think that adding something like this would induce a lot of speed penalties, since the php code isn't that heavy. But it isn't the best and nicest thing to do.

**Comment by StephanStanisic** [comment]
One of the reasons I can only change this after output has started (in a listener) is because `$Wcms->currentPage` only get's initialized in a listener.

If we could make `currentPage` available during setup of the plugin, I could send the headers in the constructor.

**Comment by robiso** [comment]
Sorry for the late responses, been extra busy lately.

Thanks for the brainstorming and everything awesome you've been doing lately. More rewards incoming soon. :)

1. Could you just set the "$currentPageExists" to true before you call the "notFoundResponse()" is called?

2. Or could the following class be extended:
```
    /**
     * 404 header response
     * @return void
     */
    public function notFoundResponse(): void
    {
        if (!$this->loggedIn && !$this->currentPageExists) {
            header('HTTP/1.1 404 Not Found');
        }
    }
```

**Comment by robiso** [comment]
Header issue fixed by @slavenstancic 🚀 
https://github.com/robiso/simple-blog/commit/c200b94f32e6ac46c65c9972b7ee98b7dee7135c
Includes some additional visual fixes.

Happily closing issue.

**Comment by StephanStanisic** [comment]
Nicely done!

**Comment by robiso** [comment]
@StephanStanisic, a great shoutout to you for creating the most (IMHO) useful plugin (shares award with Summernote editors:). 🏆

Would you like to pull this upstream of have separate forks?
